[package]
name = "stupidcube"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
strum_macros = "0.26.4"
derive-getters = "0.5.0"
crossterm = {version = "0.28.1", default-features = false}